name: CI

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:
  lint:
    name: Golang-CI Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1

  cross:
    name: Cross
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Build
        run: |
          for target in $(go tool dist list); do
            echo "Building for $target"
            GOOS=${target%/*} GOARCH=${target#*/} go build ./...
          done

  test:
    name: Unit test
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [stable, oldstable, 1.23.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -race -v ./...

  tinygo:
    name: TinyGo
    timeout-minutes: 10
    strategy:
      matrix:
        # TinyGo may not have support for all latest language features,
        # so we're pinning to a fixed version for now.
        # https://tinygo.org/docs/reference/go-compat-matrix/
        go-version: [1.26.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install TinyGo
        run: |
          tinygo_deb="tinygo_${TINYGO_VERSION}_amd64.deb"
          wget --progress=dot:giga "https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/${tinygo_deb}"
          echo "${TINYGO_CHECKSUM#sha256:} *${tinygo_deb}" | sha256sum -c -
          sudo dpkg -i "${tinygo_deb}"
          tinygo version
        env:
          TINYGO_VERSION: 0.41.1
          TINYGO_CHECKSUM: "sha256:901fbccffc61adb111656d1f907dfc21b6c499ca841b115866a0d6de2d835fbe"
      - name: Test
        # Run with "safe" tag to avoid "panic: reflect.Value has no flag field"
        # coming from go-spew (or the next testify version);
        # https://github.com/davecgh/go-spew/blob/v1.1.1/spew/bypass.go#L105-L109
        # https://github.com/stretchr/testify/blob/001eb7946baf451879253643e4ce4b38eaa0d4a7/internal/spew/bypass.go#L106-L110
        run: tinygo test -tags safe -v ./...
